version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-prod:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - "8081:80"
    command: "run"

volumes:
  osm-prod:
    external: true
  osm-tiles:
    external: true
